//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComunityConnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ist420grp7Entities : DbContext
    {
        public ist420grp7Entities()
            : base("name=ist420grp7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CCtblEvent> CCtblEvents { get; set; }
        public virtual DbSet<CCtblGuestLookUp> CCtblGuestLookUps { get; set; }
        public virtual DbSet<CCtblUser> CCtblUsers { get; set; }
    }
}
