//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComunityConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCtblGuestLookUp
    {
        public int fldEntryNo { get; set; }
        public Nullable<System.DateTime> fldEntryDateTime { get; set; }
        public int fldEventNoFK { get; set; }
        public int fldUserNoFK { get; set; }
    }
}
