//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComunityConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCtblEvent
    {
        public int fldEventNo { get; set; }
        public string fldEventName { get; set; }
        public string fldEventLocation { get; set; }
        public System.DateTime fldEventStart { get; set; }
        public System.DateTime fldEventEnd { get; set; }
        public string fldEventDescription { get; set; }
        public string fldEventCategory { get; set; }
        public bool fldTicketed { get; set; }
        public decimal fldTicketPrice { get; set; }
        public Nullable<int> fldRsvpNo { get; set; }
        public int fldMaxAttendees { get; set; }
        public System.DateTime fldEventSubmitDate { get; set; }
        public System.DateTime fldEventPostDate { get; set; }
        public Nullable<int> fldEventAvgReviewScore { get; set; }
        public Nullable<int> fldAttendeeNo { get; set; }
        public Nullable<bool> fldIsActive { get; set; }
        public Nullable<int> fldHostNoFK { get; set; }
    }
}
