//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComunityConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCtblUser
    {
        public int fldUserNo { get; set; }
        public string fldDisplayName { get; set; }
        public string fldFName { get; set; }
        public string fldLName { get; set; }
        public Nullable<bool> fldGender { get; set; }
        public string fldCity { get; set; }
        public string fldStateProvince { get; set; }
        public string fldCountry { get; set; }
        public string fldUserEmail { get; set; }
        public Nullable<System.DateTime> fldJoinDate { get; set; }
        public Nullable<int> fldNoEventsAttended { get; set; }
        public Nullable<bool> fldIsActive { get; set; }
    }
}
